name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: npm install
        run: npm install
      - name: Tests
        run: sbt tests/test
      - name: Run the Sample
        run: sbt sample/run
      - name: Test the Sample
        run: sbt sample/test

      # Scala.js test suite - separated in multiple steps to see at a glance where things fail
      - name: Fetch Scala.js sources for the test suite
        run: sbt scalajs-test-suite/fetchScalaJSSource
      - name: Compile the Scala.js test suite
        run: sbt scalajs-test-suite/Test/compile
      - name: Link the Scala.js test suite
        run: sbt scalajs-test-suite/Test/fastLinkJS
      - name: Run the Scala.js test suite
        run: sbt scalajs-test-suite/test
      - name: Link and run the Scala.js test suite with fullLinkJS
        run: sbt 'set Global/scalaJSStage := FullOptStage' scalajs-test-suite/test

      # Make sure we can emit the .wat file without crashing
      - name: Link the Scala.js test suite with PrettyPrint
        run: sbt 'set `scalajs-test-suite`/scalaJSLinkerConfig ~= { _.withPrettyPrint(true) }' scalajs-test-suite/Test/fastLinkJS

      - name: Format
        run: sbt scalafmtCheckAll
